#!/bin/bash

# output supression for configure and make steps 
# --debug-mode without output supression  
# output redirection "macro" for --debug-mode option 
# /etc/bash-completion.d script for --debug-mode option 
# colourful bash output for the different steps 
# check when debug mode is needed with functions and error codes 

# XVID 

WHITE='\033[1;37m' 
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' 

#if [ "$1" == '--debug-mode' ]; then
#	DBG='>/dev/null 2>&1';
#elif [ "$1"  ];
#	DBG=''
#fi  

#function install_xvid { 
		printf "${WHITE}Downloading XVid source code.${NC}\n" 
		curl -o xvidcore-1.3.2.tar.gz http://downloads.xvid.org/downloads/xvidcore-1.3.2.tar.gz  
		tar xf xvidcore-1.3.2.tar.gz 
		cd xvidcore/build/generic
		printf "\n"
		printf "${GREEN}Prepare, build and install Xvid source.${NC}\n" 
		./configure >/dev/null 2>&1 
		make >/dev/null 2>&1
		make install >/dev/null 2>&1
		ldconfig 
		rm  xvidcore-1.3.2.tar.gz 2>&1 
		rm -rf xvidcore/ 
		cd ..  
#		return 0 
		printf "${RED}Xvid installed successfully${NC}\n" 
		exit; 
#} 

# Lame Codec 
wget http://downloads.sourceforge.net/project/lame/lame/3.98.4/lame-3.98.4.tar.gz
tar xf lame-3.98.4.tar.gz
cd lame-3.98.4/
./configure 
make && make install 
ldconfig 
cd .. 
rm lame-3.98.4.tar.gz
rm -rf lame-3.98.4/

# FAAC Codec 
wget http://downloads.sourceforge.net/faac/faac-1.28.tar.gz
tar xf faac-1.28.tar.gz
cd faac-1.28
./bootstrap
./configure 
make && make install 
ldconfig 
cd .. 
rm faac-1.28.tar.gz
rm -rf faac-1.28/

#OpenCore AMR Codec 
wget http://downloads.sourceforge.net/project/opencore-amr/opencore-amr/0.1.2/opencore-amr-0.1.2.tar.gz
tar xf opencore-amr-0.1.2.tar.gz
cd opencore-amr-0.1.2
./configure 
make 
make install 
ldconfig 
cd ..
rm opencore-amr-0.1.2.tar.gz
rm -rf opencore-amr-0.1.2

#OGG Codec 
wget http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.xz
tar xf libogg-1.3.2.tar.xz
cd libogg-1.3.2/ 
./configure
make 
make install 
ldconfig
cd ../ 
rm libogg-1.3.2.tar.xz
rm -rf libogg-1.3.2/

#Vorbis Codec 
wget http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.5.tar.xz
tar xf libvorbis-1.3.5.tar.xz
cd libvorbis-1.3.5/ 
./configure 
make 
make install 
ldconfig 
cd ..
rm libvorbis-1.3.5.tar.xz
rm -rf libvorbis-1.3.5/

# Theora Codec 
wget http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2
tar xf libtheora-1.1.1.tar.bz2
cd libtheora-1.1.1/ 
./configure 
make 
make install 
ldconfig 
cd .. 
rm libtheora-1.1.1.tar.bz2
rm -rf libtheora-1.1.1/

# x264 
git clone git://git.videolan.org/x264.git
cd x264 
./configure --enable-static --disable-asm 
make 
make install
ldconfig 
cd ..
rm -rf x264 

# LibVPX 
git clone https://github.com/webmproject/libvpx/
cd libvpx/ 
./configure
make 
make install 
ldconfig 
cd ..
rm -rf libvpx/ 

# FFmpeg 
git clone git://git.videolan.org/ffmpeg.git ffmpeg
cd ffmpeg
./configure --enable-version3 --enable-libopencore-amrnb \
--enable-libopencore-amrwb --enable-libvpx --enable-libfaac \
--enable-libmp3lame --enable-libtheora --enable-libvorbis \
--enable-libx264 --enable-libxvid --enable-gpl --enable-postproc \
--enable-nonfree
make 
make install 
ldconfig
cd ..
rm -rf ffmpeg/
