#!/bin/bash

SOURCES_TAR=( http://downloads.sourceforge.net/project/lame/lame/3.98.4/lame-3.98.4.tar.gz
    http://downloads.sourceforge.net/project/opencore-amr/opencore-amr/0.1.2/opencore-amr-0.1.2.tar.gz
    http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.xz
	http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.5.tar.xz )

SOURCES_GIT=( https://github.com/webmproject/libvpx )

declare -A SOURCES_AAC=()

WHITE='\033[1;37m'
NC='\033[0m' 

function install_xvid { 
        curl -o xvidcore-1.3.2.tar.gz http://downloads.xvid.org/downloads/xvidcore-1.3.2.tar.gz
        tar xf xvidcore-1.3.2.tar.gz
        cd xvidcore/build/generic
        #printf "\n"
        #printf "${GREEN}Prepare, build and install Xvid source.${NC}\n"
        ./configure >/dev/null # 2>&1
        make >/dev/null #2>&1
        make install >/dev/null #2>&1
        ldconfig
        cd ..
        rm -rf xvidcore*
        #printf "${RED}Xvid installed successfully${NC}\n"
} 

function install_from_tar {
    URL="$1"
    FILE=$(echo $URL | awk -F "/" '{print $NF}' )
    DIR=$(echo $FILE | sed 's|.tar.*||g' )
    wget $URL
    tar xf $FILE
    cd $DIR
    ./configure
    make
    make install
    ldconfig
    cd ..
    rm -rf $DIR
    rm $FILE
}

function install_from_git {
    REPO="$1"
    DIR=$(echo $REPO | awk -F "/" '{print $NF}' | sed 's|.git||g' )
	printf "${WHITE}Downloading $DIR source code.${NC}"
	git clone $REPO
    cd $DIR
    ./configure
    make
    make install
    ldconfig
    cd ..
    rm -rf $DIR
	return 0 
}

function install_x264 { 
		git clone git://git.videolan.org/x264.git
		cd x264
		./configure --enable-static --disable-asm
		make
		make install
		ldconfig
		cd ..
		rm -rf x264
} 

function install_faac { 
		wget http://downloads.sourceforge.net/faac/faac-1.28.tar.gz
		tar xf faac-1.28.tar.gz
		cd faac-1.28
		sed -i '126d' common/mp4v2/mpeg4ip.h
		./bootstrap
		./configure
		make && make install
		ldconfig
		cd ..
		rm faac-1.28.tar.gz
		rm -rf faac-1.28/
} 

install_xvid
install_x264
install_faac 
for i in ${SOURCES_TAR[@]} ; do install_from_tar $i; done 
for y in ${SOURCES_GIT[@]}; do install_from_git $y; done 

git clone git://git.videolan.org/ffmpeg.git ffmpeg
cd ffmpeg
./configure --enable-version3 --enable-libopencore-amrnb --enable-libmp3lame \
--enable-libopencore-amrwb --enable-libvpx --enable-libfaac \
--enable-libmp3lame --enable-libtheora --enable-libvorbis \
--enable-libx264 --enable-libxvid --enable-gpl --enable-postproc \
--enable-nonfree
make
make install
ldconfig
cd ..
rm -rf ffmpeg/
